name: dupplifilter
description: DuppliFilter iOS App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5
  share_plus: ^6.3.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true